# Generated by Django 5.2.7 on 2025-10-18 11:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0002_rename_product_order_products'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='strock',
            new_name='stock',
        ),
    ]
