# Generated by Django 5.2.7 on 2025-10-18 19:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0004_remove_order_products_order_products'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2025, 10, 18, 19, 38, 31, 209702, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
